security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        from_database:
            entity:
                # the class of the entity that represents users
                class: App\Entity\Member
                # the property to query by - e.g. username, email, etc
                property: pseudo
                # managers, this option defines which one to use
                # manager_name: 'customer'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true

            # activate different ways to authenticate
            logout:
                path: /deconnexion
                target: /

            form_login:
                check_path: login


    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/mentions-legales, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
    
    encoders:
        App\Entity\Member:
            # bcrypt or argon2i are recommended
            # argon2i is more secure, but requires PHP 7.2 or the Sodium extension
            algorithm: bcrypt
            cost: 12
